"""Mouse + keyboard humanizer for executor browser tools.

Real users move the mouse along curved paths with non-uniform speed and
type with variable inter-key delays. Naive Playwright ``click()`` and
``type()`` calls teleport the mouse and emit perfectly-spaced keypresses,
which is a tell some bot-detection systems (Datadome, PerimeterX, Akamai)
look for.

This module provides three helpers that augment :meth:`Page.mouse.move`
+ :meth:`Page.mouse.click` and :meth:`Page.keyboard.type` with subtle
humanization. All randomness flows through an injectable ``random.Random``
so tests can pin a seed and assert deterministic behaviour.

Cost is intentionally bounded: ``low`` intensity (default) adds roughly
150 ms per action; ``off`` is a passthrough.
"""

from __future__ import annotations

import asyncio
import contextlib
import random
from dataclasses import dataclass
from typing import Any

# ---------------------------------------------------------------------------
# Intensity profiles
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class IntensityProfile:
    """Mean values for the random distributions used by the humanizer."""

    waypoints: int  # 0 = teleport (no humanization)
    move_segment_ms: float
    inter_key_ms: float
    dwell_ms: float
    fill_clear_dwell_ms: float


PROFILES: dict[str, IntensityProfile] = {
    "off": IntensityProfile(
        waypoints=0,
        move_segment_ms=0.0,
        inter_key_ms=0.0,
        dwell_ms=0.0,
        fill_clear_dwell_ms=0.0,
    ),
    "low": IntensityProfile(
        waypoints=2,
        move_segment_ms=60.0,
        inter_key_ms=80.0,
        dwell_ms=30.0,
        fill_clear_dwell_ms=40.0,
    ),
    "medium": IntensityProfile(
        waypoints=3,
        move_segment_ms=120.0,
        inter_key_ms=140.0,
        dwell_ms=50.0,
        fill_clear_dwell_ms=80.0,
    ),
    "high": IntensityProfile(
        waypoints=4,
        move_segment_ms=180.0,
        inter_key_ms=200.0,
        dwell_ms=80.0,
        fill_clear_dwell_ms=120.0,
    ),
}

VALID_INTENSITIES: tuple[str, ...] = tuple(PROFILES.keys())


def normalize_intensity(value: str | None) -> str:
    """Coerce an intensity string into a known profile name."""
    if not value:
        return "low"
    norm = str(value).strip().lower()
    return norm if norm in PROFILES else "low"


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _jitter(rng: random.Random, mean_ms: float) -> float:
    """Sample a non-negative duration around ``mean_ms`` (sigma = mean/4)."""
    if mean_ms <= 0:
        return 0.0
    sigma = max(1.0, mean_ms / 4.0)
    sample = rng.gauss(mean_ms, sigma)
    return max(0.0, sample)


def _bezier_path(
    *,
    rng: random.Random,
    start: tuple[float, float],
    end: tuple[float, float],
    waypoints: int,
) -> list[tuple[float, float]]:
    """Build a cubic-Bezier-ish path of ``waypoints + 2`` points (start..end).

    The curve is generated by sampling a quadratic/cubic Bezier with random
    control points biased into the bounding box of the segment.
    """
    if waypoints <= 0:
        return [start, end]

    sx, sy = start
    ex, ey = end
    dx = ex - sx
    dy = ey - sy

    # Random control points around the midpoint, biased to make the curve
    # look like a natural reach (some perpendicular bow).
    perp_x = -dy
    perp_y = dx
    bow = rng.uniform(-0.25, 0.25)
    cx = sx + dx * 0.5 + perp_x * bow
    cy = sy + dy * 0.5 + perp_y * bow

    # Sample ``waypoints`` intermediate points along a quadratic Bezier
    # (start, control, end). Higher-intensity profiles get more points so
    # the path looks smoother.
    points: list[tuple[float, float]] = [start]
    for index in range(1, waypoints + 1):
        t = index / (waypoints + 1)
        # quadratic Bezier
        x = (1 - t) ** 2 * sx + 2 * (1 - t) * t * cx + t**2 * ex
        y = (1 - t) ** 2 * sy + 2 * (1 - t) * t * cy + t**2 * ey
        # small per-point jitter so consecutive points aren't perfectly
        # collinear in extreme cases
        x += rng.uniform(-1.5, 1.5)
        y += rng.uniform(-1.5, 1.5)
        points.append((x, y))
    points.append(end)
    return points


async def _sleep_ms(ms: float) -> None:
    if ms <= 0:
        return
    await asyncio.sleep(ms / 1000.0)


async def _bounding_centre(locator: Any) -> tuple[float, float] | None:
    """Return (x, y) of the centre of ``locator`` or ``None`` when unknown."""
    try:
        box = await locator.bounding_box()
    except Exception:
        return None
    if not box:
        return None
    try:
        return (
            float(box["x"]) + float(box["width"]) / 2.0,
            float(box["y"]) + float(box["height"]) / 2.0,
        )
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def humanize_click(
    page: Any,
    locator: Any,
    *,
    intensity: str = "low",
    rng: random.Random | None = None,
    button: str = "left",
    click_count: int = 1,
) -> None:
    """Click ``locator`` with a humanized mouse path."""
    profile = PROFILES[normalize_intensity(intensity)]
    if profile.waypoints <= 0:
        await locator.click(button=button, click_count=click_count)
        return

    rng = rng or random.Random()
    start = (rng.uniform(40, 120), rng.uniform(40, 120))
    end = await _bounding_centre(locator)
    if end is None:
        await locator.click(button=button, click_count=click_count)
        return

    path = _bezier_path(rng=rng, start=start, end=end, waypoints=profile.waypoints)
    for px, py in path:
        try:
            await page.mouse.move(px, py, steps=1)
        except Exception:
            # If mouse.move is unavailable (some headless modes), fall back.
            await locator.click(button=button, click_count=click_count)
            return
        await _sleep_ms(_jitter(rng, profile.move_segment_ms))
    await _sleep_ms(_jitter(rng, profile.dwell_ms))
    try:
        await page.mouse.down(button=button)
        await _sleep_ms(_jitter(rng, profile.dwell_ms))
        await page.mouse.up(button=button)
        if click_count > 1:
            for _ in range(click_count - 1):
                await _sleep_ms(_jitter(rng, profile.dwell_ms))
                await page.mouse.down(button=button)
                await page.mouse.up(button=button)
    except Exception:
        await locator.click(button=button, click_count=click_count)


async def humanize_type(
    page: Any,
    locator: Any,
    text: str,
    *,
    intensity: str = "low",
    rng: random.Random | None = None,
) -> None:
    """Type ``text`` into ``locator`` with humanized inter-key delays."""
    profile = PROFILES[normalize_intensity(intensity)]
    if profile.waypoints <= 0 or profile.inter_key_ms <= 0:
        await locator.type(text)
        return

    rng = rng or random.Random()
    # Make sure the locator is focused; humanize the focus click too.
    try:
        await humanize_click(page, locator, intensity=intensity, rng=rng)
    except Exception:
        try:
            await locator.focus()
        except Exception:
            await locator.click()

    for char in text:
        try:
            await page.keyboard.type(char)
        except Exception:
            await locator.type(char)
        await _sleep_ms(_jitter(rng, profile.inter_key_ms))


async def humanize_fill(
    page: Any,
    locator: Any,
    value: str,
    *,
    intensity: str = "low",
    rng: random.Random | None = None,
) -> None:
    """Replace ``locator``'s value with humanized clear + type."""
    profile = PROFILES[normalize_intensity(intensity)]
    if profile.waypoints <= 0:
        await locator.fill(value)
        return

    rng = rng or random.Random()
    try:
        await humanize_click(page, locator, intensity=intensity, rng=rng, click_count=3)
    except Exception:
        try:
            await locator.click(click_count=3)
        except Exception:
            await locator.click()
    await _sleep_ms(_jitter(rng, profile.fill_clear_dwell_ms))
    try:
        await page.keyboard.press("Delete")
    except Exception:
        with contextlib.suppress(Exception):
            await locator.fill("")
    await humanize_type(page, locator, value, intensity=intensity, rng=rng)
